data_set:
  type: CIFAR10
data_augmentation:
  type: CIFAR10AlbumentationS9
model:
  type: CustomResnet
input_size:
  value: (3, 32, 32)
mean:
  value: (0.4914, 0.4822, 0.4465)
std:
  value: (0.247, 0.243, 0.261)
max_lr:
  value: 0.02
min_lr:
  value: 0.001
lr_finder_epochs:
  value: 10
momentum:
  value: 0.9
weight_decay:
  value: 0.05
optimizer_weight_decay:
  value: 0.005
learning_rate:
  value: 0.01
train_epochs:
  value: 24 
pct_start:
  value: 0.167  
anneal_strategy:
  value: 'linear'  
cycle_momentum:
  value: False  
base_momentum:
  value: 0.85  
max_momentum:
  value: 0.95  
div_factor:
  value: 10.0  
final_div_factor:
  value: 1
classes:
  value: ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']